site_name: EMBER Docs
repo_name: aplbrain/bbqs-ember-docs
repo_url: https://github.com/aplbrain/BBQS-EMBER-docs

theme:
  name: material
  language: en
  logo: assets/ember-logo.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
  - User Guide:
    - Overview: user-guide/index.md
    # - user-guide/uploading-data.md
    # - user-guide/downloading-data.md
