site_name: EMBER Docs
repo_name: aplbrain/bbqs-ember-docs
repo_url: https://github.com/aplbrain/BBQS-EMBER-docs

theme:
  name: material
  language: en
  logo: assets/ember-logo.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
  - User Guide:
    - Overview: user-guide/index.md
    - Standardizing Data:
      - 'Overview': user-guide/standardizing-EMBERDANDI.md
      - 'Detailed Instructions': user-guide/data-standardization.md
    - 'EMBER-DANDI': 
      - 'Account Creation': user-guide/EMBER-DANDI-account.md
      - 'Uploading Data': user-guide/uploading-data.md
      - 'Downloading Data': user-guide/downloading-data.md
    - 'EMBER-Vault':
      - 'Account Creation': user-guide/embervault-account.md
      - 'Uploading Data': user-guide/embervault-uploading-data.md
   
  - Example Standardization and Reproducibility: example-standardization-and-reproducibility/Suthana_Zenodo.md
